In [26]:
### each label dice comparispon
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statistics
import os
import csv
from tabulate import tabulate

generalPath = 'result_test/abstractresult/thorough/unet1x1'

# Function to extract numeric part from folder name
def extract_number(folder_name):
    return int(folder_name.split('-')[-1])
# Get a list of folder names sorted by the numeric part
dice_fold_value = []
all_data = []
#folder_names = sorted([folder_name for folder_name in os.listdir('result_test') if folder_name.startswith('20240704-Conv1x1-'+str(i)+'-')], key=extract_number)
#folder_names = sorted([folder_name for folder_name in os.listdir('result_test/abstractresult/thorough/unetpure') if folder_name.startswith('20241029-Conv1x1-'+str(i)+'-')], key=extract_number)
folder_names = sorted([folder_name for folder_name in os.listdir(generalPath) if folder_name.startswith('20241029-Conv1x1-')], key=extract_number)
print(folder_names)
# Loop through sorted folder names
for folder_name in folder_names:
    folder_path = os.path.join(generalPath, folder_name)
    if os.path.isdir(folder_path):
        # Find CSV file in the folder
        csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]
        if len(csv_files) == 2:
            if(csv_files[0].startswith('Dice')):
                csv_file_path = os.path.join(folder_path, csv_files[0])
            else:
                csv_file_path = os.path.join(folder_path, csv_files[1])
            # Read CSV file
            with open(csv_file_path, 'r') as file:
                reader = csv.reader(file)
                # Extract second number from the array
                for row in reader:
                    all_data.append(row[-1])
all_data = np.array(all_data)
all_data = all_data.astype(float)

reshaped_list = [all_data[i:i+3] for i in range(0, len(all_data), 3)]               
for index, fold in enumerate(reshaped_list):
    print("Fold:" + str(index+1))
    mean_val = np.mean(fold)
    print(fold)
    print('Avg: ' + str(mean_val))
    
    
#print(tabulate(all_data))
#all_data = np.array(all_data)
#all_data = all_data.astype(float)
#mean_val = np.mean(all_data)
#dice_fold_value.append(mean_val)
#print(mean_val)


#print("Each fold: " + '\n' + str(dice_fold_value))
#print("Mean of folds: " + str(np.mean(dice_fold_value)))


['20241029-Conv1x1-13', '20241029-Conv1x1-14', '20241029-Conv1x1-15', '20241029-Conv1x1-16', '20241029-Conv1x1-17', '20241029-Conv1x1-18', '20241029-Conv1x1-19', '20241029-Conv1x1-20', '20241029-Conv1x1-21', '20241029-Conv1x1-22', '20241029-Conv1x1-23', '20241029-Conv1x1-24']
Fold:1
[0.85880444 0.83404233 0.79418054]
Avg: 0.8290091045724876
Fold:2
[0.76140331 0.75958848 0.76114862]
Avg: 0.7607134741806495
Fold:3
[0.79774795 0.80881819 0.75763211]
Avg: 0.7880660854604767
Fold:4
[0.74748114 0.77302178 0.74570666]
Avg: 0.7554031952705752
