In [48]:
### each label dice comparispon
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statistics
import os
import csv
from tabulate import tabulate

generalPath = 'result_test/abstractresult/thorough/unetpure'

# Function to extract numeric part from folder name
def extract_number(folder_name):
    return int(folder_name.split('-')[-1])
# Get a list of folder names sorted by the numeric part
dice_fold_value = []
all_data = []
#folder_names = sorted([folder_name for folder_name in os.listdir('result_test') if folder_name.startswith('20240704-Conv1x1-'+str(i)+'-')], key=extract_number)
#folder_names = sorted([folder_name for folder_name in os.listdir('result_test/abstractresult/thorough/unetpure') if folder_name.startswith('20241029-Conv1x1-'+str(i)+'-')], key=extract_number)
folder_names = sorted([folder_name for folder_name in os.listdir(generalPath) if folder_name.startswith('20241029-Conv1x1-')], key=extract_number)
print(folder_names)
# Loop through sorted folder names
for folder_name in folder_names:
    folder_path = os.path.join(generalPath, folder_name, 'crf')
    if os.path.isdir(folder_path):
        # Find CSV file in the folder
        csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]
        csv_file_path = ''
        for csv_file in csv_files:
            if(csv_file.startswith('CRF')):
                csv_file_path = os.path.join(folder_path, csv_file)
            # Read CSV file
        with open(csv_file_path, 'r') as file:
            reader = csv.reader(file)
            # Extract second number from the array
            for row in reader:
                all_data.append(row[-1])
all_data = np.array(all_data)
all_data = all_data.astype(float)

print(all_data)

reshaped_list = [all_data[i:i+3] for i in range(0, len(all_data), 3)]               
for index, fold in enumerate(reshaped_list):
    print("Fold:" + str(index+1))
    mean_val = np.mean(fold)
    print(fold)
    print('Avg: ' + str(mean_val))
    
    
#print(tabulate(all_data))
#all_data = np.array(all_data)
#all_data = all_data.astype(float)
#mean_val = np.mean(all_data)
#dice_fold_value.append(mean_val)
#print(mean_val)


#print("Each fold: " + '\n' + str(dice_fold_value))
#print("Mean of folds: " + str(np.mean(dice_fold_value)))


['20241029-Conv1x1-1', '20241029-Conv1x1-2', '20241029-Conv1x1-3', '20241029-Conv1x1-4', '20241029-Conv1x1-5', '20241029-Conv1x1-6', '20241029-Conv1x1-7', '20241029-Conv1x1-8', '20241029-Conv1x1-9', '20241029-Conv1x1-10', '20241029-Conv1x1-11', '20241029-Conv1x1-12']
[0.83778076 0.75847466 0.74357223 0.70227044 0.74546836 0.74116278
 0.75630558 0.84600465 0.8107654  0.79479163 0.79268107 0.78922734]
Fold:1
[0.83778076 0.75847466 0.74357223]
Avg: 0.7799425518685172
Fold:2
[0.70227044 0.74546836 0.74116278]
Avg: 0.729633858915829
Fold:3
[0.75630558 0.84600465 0.8107654 ]
Avg: 0.8043585454233181
Fold:4
[0.79479163 0.79268107 0.78922734]
Avg: 0.7922333456606186
