In [13]:
import cv2
import numpy as np

img = cv2.imread("N3-3.png", cv2.IMREAD_GRAYSCALE)

print(img)

px_value_ls = img.tolist()

mean = np.round(np.mean(px_value_ls))

total = 0

for x in px_value_ls:
    nmb = (x - mean) ** 2
    total += nmb
    
std_dev = total / len(px_value_ls)


for x in px_value_ls:
    print(x-std_dev)
    x = np.abs(x-std_dev)
    
image_array = np.array(px_value_ls, dtype=np.uint8)

# Save or display the image
cv2.imwrite('filter_test.jpg', image_array)  

[[ 56  62  68 ... 159 113  72]
 [ 58  60  71 ... 152 112  67]
 [ 53  58  72 ... 146 104  68]
 ...
 [  5   4   4 ...  13  13  11]
 [  4   4   4 ...  12   9   9]
 [  4   4   5 ...  12   8   9]]
[-11236.5859375  -11157.26953125 -11116.33984375 -11084.59375
 -11031.421875   -10993.         -10974.734375   -10924.93359375
 -10886.94921875 -10833.96484375 -10830.578125   -10762.703125
 -10730.4765625  -10690.1875     -10634.69140625 -10609.65234375
 -10535.74609375 -10457.296875   -10367.55078125 -10292.25390625
 -10244.27734375 -10154.921875   -10070.46875    -10001.44921875
  -9940.54296875  -9914.9609375   -9814.44921875  -9737.03125
  -9679.6171875   -9606.0390625   -9494.50390625  -9398.17578125
  -9272.203125    -9191.46484375  -9137.96484375  -9050.16796875
  -8973.296875    -8873.0625      -8758.51171875  -8667.84765625
  -8633.25390625  -8548.3203125   -8526.53125     -8442.95703125
  -8425.46484375  -8363.4921875   -8333.84765625  -8258.58984375
  -8206.8984375   -8212.11328125  -8

True